spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA5BXSQ/I40fHXAd15HNGQLAEM/TsfTI39FNTb55C/RolGexp4ZOsQBxy6DhP78lptMgtoENKLSCq3fFs8pmIt2NI7x/pUKvffdEmw036CgJblOtTloZusGsFbykGRmPUT8dxbJIAGK3uQzFczTcXE/d/uGOluq2KxMOpraJ7UvSa36QfWnat9pZ5DN9xAG+yaD8MF4Mc1NqgUWgmCTxzZCvdCZzWh48Ol0W/roNKJEz+pX0MrTTROOlVhhzlKKVEgnzy48k3ypdVeUroAVDiCWUHBb+MTG7xazOcQXhXZ1tO9kxi+n/dAOLaHkQhxXD37wkViLtj7Q4TsdgW3U2DH4e+m30fEJFa5FFh+aSyvhkHgUk47Q1jXOGmbbWzcV8ro='

token:
  expiration_time: 86400000
  secret: user_token_native_user_service

gateway:
  ip: 192.168.219.101

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
