server:
  port: 9001

spring:
  application:
    name: user-service

# fetch-registry : eureka ????? ???? ??? ????? ?????? ??.
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZon: http://127.0.0.1:8761/eureka
